### ISSUE TITLE
Can't change Map address

### ISSUE THREAD

**Issue by NicolaAntoniazzi** [BlackrockDigital/startbootstrap-stylish-portfolio#15]
Hi!, i'm try to changeing the address shown on the map by changeing the urls with the google Map's one that i want to show........ how can i solve this problem?

**Comment by jawadnassar** [comment]
Hi, go to maps.google.com link of your address and click Menu
(near the search bar)** --> **Share or embed map** -->** Embed map.
you'll get a code like the one below.

```
<iframe 
src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13248.159262871146!2d35.495479399999994!3d33.8886284!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x151f17215880a78f%3A0x729182bae99836b4!2sBeirut%2C+Lebanon!5e0!3m2!1sen!2s!4v1439029945713" 
width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

```

 replace *YOUR_MAP_URL* by the source link (found inside src attribute)
 
```
<!-- Map -->
<section id="contact" class="map">
   <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" 
   src="YOUR_MAP_URL"></iframe>
   <br />
   <small>
       <a href="YOUR_MAP_URL"></a>
   </small>
   </iframe>
</section>
```
for more information about google maps embed api check google developers
[website](https://developers.google.com/maps/documentation/embed/guide).

**Comment by NicolaAntoniazzi** [comment]
OK, it worked, thanks

Il giorno sab 8 ago 2015 13:53 Jawad Nassar <notifications@github.com> ha
scritto:

> Hi, go to maps.google.com link of your address and click Menu
> (near the search bar)** --> *Share or embed map* -->** Embed map.
> you'll get a code like the one below.
>
> <iframe
> src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13248.159262871146!2d35.495479399999994!3d33.8886284!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x151f17215880a78f%3A0x729182bae99836b4!2sBeirut%2C+Lebanon!5e0!3m2!1sen!2s!4v1439029945713"
> width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
>
>
> replace *YOUR_MAP_URL* by the source link (found inside src attribute)
>
> 
> <section id="contact" class="map">
>    <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
>    src="YOUR_MAP_URL"></iframe>
>    <br />
>    <small>
>        <a href="YOUR_MAP_URL"></a>
>    </small>
>    </iframe>
> </section>
>
> for more information about google maps embed api check google developers
> website <https://developers.google.com/maps/documentation/embed/guide>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IronSummitMedia/startbootstrap-stylish-portfolio/issues/15#issuecomment-128971059>
> .
>
-- 
Antoniazzi Nicola
Tel. 334/2010474
