### ISSUE TITLE
Map Takes Scroll Control

### ISSUE THREAD

**Issue by stephen-cernota** [BlackrockDigital/startbootstrap-stylish-portfolio#19]
On my PC, when scrolling down the page, the map takes scroll control

Demo Page: http://ironsummitmedia.github.io/startbootstrap-stylish-portfolio/

First time I thought that was weird but intended behavior, I actually didn't know there was more at the bottom of the page below the map

== Potential Fixes?

IronSummitMedia/startbootstrap-stylish-portfolio
https://github.com/IronSummitMedia/startbootstrap-stylish-portfolio/pull/9 Disable google maps scrolling hijack unless clicked  

volny/stylish-portfolio-jekyll
Map widget captures scroll
Issue: https://github.com/volny/stylish-portfolio-jekyll/issues/1
Commit: https://github.com/volny/stylish-portfolio-jekyll/commit/318f311d282351892db44808c56ceceb8c11b075

**Comment by davidtmiller** [comment]
Fixed!
