### ISSUE TITLE
Newsletter form

### ISSUE THREAD

**Issue by federicovilla** [BlackrockDigital/startbootstrap-stylish-portfolio#31]
Great free template...really thanks for this.
Just a request..not an issue of course: how about adding a simple form, for example for subscribing a newsletter?
Thanks

**Comment by davidtmiller** [comment]
A good way to do it is to sign up for a MailChimp account or some other newsletter and get their custom code that you can drop into your HTML. After that, look at the Bootstrap docs at getbootstrap.com and look to their form documentation for the classes you need to add to the HTML form you get from your newsletter provider. Hopefully this helps!
