### ISSUE TITLE
Creating a Contact Page with Python Django 

### ISSUE THREAD

**Issue by SimasJan** [BlackrockDigital/startbootstrap-stylish-portfolio#65]
Hi, apologies upfront if the question appears to be silly. 

I understand it is a one-page template, yet I would like to ask whether you are able to add links to that would direct user to other pages, for example the Contact Page ? 

Thank you. 

P.S. I am using Python Django backend framework.

**Comment by davidtmiller** [comment]
Yes you can add other pages. The best way to do this would probably to be using the menu bar as a component, and then linking out other pages using that. The menu bar, footer, and CSS/JS should remain consistent across all pages, but other pages you can modify as you please!
