### ISSUE TITLE
resolution for smartphone

### ISSUE THREAD

**Issue by Vacuolino** [BlackrockDigital/startbootstrap-stylish-portfolio#67]
hi

In my smartphone i don't see the pictures in full frame because the pictures are crop, how do i do to modify thi parameter?

Thank you

**Comment by davidtmiller** [comment]
They resize due to the background cover rule. Pictures fill the size of the box, so they resize automatically - if the image is being cropped in a way you don't like at certain positions then you can change the `background-position` at different screen sizes using CSS media queries.
