### ISSUE TITLE
Gulp 4 issues

### ISSUE THREAD

**Issue by kp-online** [BlackrockDigital/startbootstrap-stylish-portfolio#81]
Hi,

I just tried to use your template and realised a minor error has appeared in the gulpfile.js after updating to gulp 4.0.

The command `gulp watch` is not available in its current form.

I modified the watch command to be:
```
gulp.task('watch', function () {
  gulp.series(build, gulp.parallel(watchFiles, browserSync));
});
```

This works, but I'm not sure if this is a proper fix.

**Comment by davidtmiller** [comment]
This should be fixed as of now, I would use `npm start` now as well to make things easier.
